// Wails bridge - wraps auto-generated bindings with error handling
// Note: The actual wailsjs/go/main/App bindings are auto-generated by Wails
// This module provides a clean interface for calling them

import * as App from '../../wailsjs/go/main/App'
import { EventsOn } from '../../wailsjs/runtime/runtime'

// Dashboard methods
export async function getDashboardSummary(period = 'month') {
  try {
    return await App.GetDashboardSummary(period)
  } catch (err) {
    console.error('Failed to fetch dashboard summary:', err)
    throw err
  }
}

export async function getSpendOverTime(period = 'month', granularity = 'daily') {
  try {
    return await App.GetSpendOverTime(period, granularity)
  } catch (err) {
    console.error('Failed to fetch spend over time:', err)
    throw err
  }
}

export async function getUsageByProvider(period = 'month') {
  try {
    return await App.GetUsageByProvider(period)
  } catch (err) {
    console.error('Failed to fetch usage by provider:', err)
    throw err
  }
}

export async function getUsageByModel(period = 'month') {
  try {
    return await App.GetUsageByModel(period)
  } catch (err) {
    console.error('Failed to fetch usage by model:', err)
    throw err
  }
}

export async function getTokenRatio(period = 'month') {
  try {
    return await App.GetTokenRatio(period)
  } catch (err) {
    console.error('Failed to fetch token ratio:', err)
    throw err
  }
}

// History methods
export async function getUsageEvents(filter) {
  try {
    return await App.GetUsageEvents(filter)
  } catch (err) {
    console.error('Failed to fetch usage events:', err)
    throw err
  }
}

export async function exportUsageEvents(filter, format = 'csv') {
  try {
    return await App.ExportUsageEvents(filter, format)
  } catch (err) {
    console.error('Failed to export events:', err)
    throw err
  }
}

// Provider methods
export async function listProviders() {
  try {
    return await App.ListProviders()
  } catch (err) {
    console.error('Failed to list providers:', err)
    throw err
  }
}

export async function addProvider(id, apiKey) {
  try {
    return await App.AddProvider(id, apiKey)
  } catch (err) {
    console.error('Failed to add provider:', err)
    throw err
  }
}

export async function updateProviderKey(id, apiKey) {
  try {
    return await App.UpdateProviderKey(id, apiKey)
  } catch (err) {
    console.error('Failed to update provider key:', err)
    throw err
  }
}

export async function removeProvider(id) {
  try {
    return await App.RemoveProvider(id)
  } catch (err) {
    console.error('Failed to remove provider:', err)
    throw err
  }
}

export async function testProviderConnection(id) {
  try {
    return await App.TestProviderConnection(id)
  } catch (err) {
    console.error('Failed to test connection:', err)
    throw err
  }
}

export async function syncProvider(id) {
  try {
    return await App.SyncProvider(id)
  } catch (err) {
    console.error('Failed to sync provider:', err)
    throw err
  }
}

export async function syncAll() {
  try {
    return await App.SyncAll()
  } catch (err) {
    console.error('Failed to sync all:', err)
    throw err
  }
}

// Project methods
export async function listProjects() {
  try {
    return await App.ListProjects()
  } catch (err) {
    console.error('Failed to list projects:', err)
    throw err
  }
}

export async function createProject(name, color) {
  try {
    return await App.CreateProject(name, color)
  } catch (err) {
    console.error('Failed to create project:', err)
    throw err
  }
}

export async function updateProject(id, name, color) {
  try {
    return await App.UpdateProject(id, name, color)
  } catch (err) {
    console.error('Failed to update project:', err)
    throw err
  }
}

export async function deleteProject(id) {
  try {
    return await App.DeleteProject(id)
  } catch (err) {
    console.error('Failed to delete project:', err)
    throw err
  }
}

// Budget methods
export async function getBudgets() {
  try {
    return await App.GetBudgets()
  } catch (err) {
    console.error('Failed to get budgets:', err)
    throw err
  }
}

export async function setBudget(scope, monthlyLimitUSD, thresholds) {
  try {
    return await App.SetBudget(scope, monthlyLimitUSD, thresholds)
  } catch (err) {
    console.error('Failed to set budget:', err)
    throw err
  }
}

export async function deleteBudget(scope) {
  try {
    return await App.DeleteBudget(scope)
  } catch (err) {
    console.error('Failed to delete budget:', err)
    throw err
  }
}

export async function getBudgetStatus() {
  try {
    return await App.GetBudgetStatus()
  } catch (err) {
    console.error('Failed to get budget status:', err)
    throw err
  }
}

// Settings methods
export async function getSettings() {
  try {
    return await App.GetSettings()
  } catch (err) {
    console.error('Failed to get settings:', err)
    throw err
  }
}

export async function updateSettings(settings) {
  try {
    return await App.UpdateSettings(settings)
  } catch (err) {
    console.error('Failed to update settings:', err)
    throw err
  }
}

export async function getDataStats() {
  try {
    return await App.GetDataStats()
  } catch (err) {
    console.error('Failed to get data stats:', err)
    throw err
  }
}

export async function exportAllData(format = 'db') {
  try {
    return await App.ExportAllData(format)
  } catch (err) {
    console.error('Failed to export all data:', err)
    throw err
  }
}

// Sync methods
export async function getLastSyncTimes() {
  try {
    return await App.GetLastSyncTimes()
  } catch (err) {
    console.error('Failed to get sync times:', err)
    throw err
  }
}

export async function importData(filepath) {
  try {
    return await App.ImportData(filepath)
  } catch (err) {
    console.error('Failed to import data:', err)
    throw err
  }
}

// Event listeners
export function onSyncStarted(callback) {
  EventsOn('sync:started', callback)
}

export function onSyncCompleted(callback) {
  EventsOn('sync:completed', callback)
}

export function onSyncFailed(callback) {
  EventsOn('sync:failed', callback)
}

export function onBudgetAlert(callback) {
  EventsOn('budget:alert', callback)
}

export function onLogParsed(callback) {
  EventsOn('log:parsed', callback)
}
